# This workflow publishes the module to Maven and is triggered when a Draft release is published.

name: Publish Release

on:
  release:
    types: [released]

jobs:
  upload_to_maven_central:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup git config
      run: |
        git config user.name "release-bot"
        git config user.email "<>"

    - name: Get version from tag
      id: get_version
      run: |
        releaseVersion="${GITHUB_REF/refs\/tags\//}"
        releaseVersion="${releaseVersion//v/}"
        echo "VERSION=$releaseVersion" >> $GITHUB_OUTPUT 

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Update version pom.xml
      run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

    - name: Install gpg key
      run: echo -e "${{ secrets.GPG_SECRET_KEY }}" | base64 --decode | gpg --batch --import

    - name: Publish
      run: mvn --no-transfer-progress --batch-mode deploy -P release
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_KEY_PASS_PHRASE }}

    - name: Bump version
      run: .ci/scripts/bump-version.sh
